### ISSUE TITLE
filter quotes by character name

### ISSUE THREAD

**Issue by RocktimSaikia** [RocktimSaikia/anime-chan#11]
make a new route where users can query quotes by the character name.
Basically we need to this route available `api/quotes?char=naruto`.

there are some things you need to consider before coding. I'll share them once someone picks this issue!

**Comment by yonis9** [comment]
Hi, can I take it?

**Comment by RocktimSaikia** [comment]
@yonis9  sure. Use the `slugs` to filter the data. I have added slug for both `anime` and `char` object in every quote in database.  Generate a slug of the passed `char` value and query it.
Basically just like I did with `anime` filter query . and define the new  method in `/utils/query.js`.  If you need nay help . you can ask me :)

**Comment by RocktimSaikia** [comment]
I also need to add some sample data on the repo for other developers to work on the local environment.

**Comment by yonis9** [comment]
I have some issues with connecting the database. I've created the .env file, is there something else I need to configure?

**Comment by RocktimSaikia** [comment]
it's because I forgot to add the sample data in the repo for testing. I'm doing it now. ill update you

**Comment by RocktimSaikia** [comment]
@yonis9 I updated repo also removed the `example .env`  and added an actual `.env` file for local development. It should be working now. let me know
