### ISSUE TITLE
Please enable CORS

### ISSUE THREAD

**Issue by cr7yash** [RocktimSaikia/anime-chan#13]
"Access to XMLHttpRequest at 'https://anime-chan.herokuapp.com/api/quotes?anime=naruto' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource."

**Comment by RocktimSaikia** [comment]
@cr7yash it has been added in the recent commit. thanks for submitting the issue :)
