### ISSUE TITLE
An issue with query by an anime series name

### ISSUE THREAD

**Issue by valkyrie-max** [RocktimSaikia/anime-chan#15]
I've noticed that no matter what name I put instead of "naruto", it will still return Naruto quotes and not the anime I've put. 

`https://anime-chan.herokuapp.com/api/quotes?anime=hyouka`

behaves the same way as

`https://anime-chan.herokuapp.com/api/quotes?anime=naruto`

**Comment by RocktimSaikia** [comment]
@valkyrie-max  thanks for pointing it out. I forgot to update the production version of the api with the new changes. I updated it , should be fine now. 
I am mostly busy with internship and other personal projects these days so it becomes hard manage all the projects . again thanks for pointing it out :)

**Comment by valkyrie-max** [comment]
@RocktimSaikia Oh, I totally understand! Thank you for creating this API in the first place! I sent you an email a while back ago about asking whether or not I could use it for my project (with the credit, obviously).
I hope you are enjoying your internship!
