### ISSUE TITLE
Not really an issue but rather a suggestion

### ISSUE THREAD

**Issue by valkyrie-max** [RocktimSaikia/anime-chan#16]
When getting ten quotes by default, I think it would be awesome if they are 10 random quotes instead of an established set.

**Comment by RocktimSaikia** [comment]
@valkyrie-max thanks for the suggestion :). I will try to implement asap

**Comment by RocktimSaikia** [comment]
@valkyrie-max here is the few changes : 
1. Query quotes through character name is availabe now.
2. Randomized the returnring the data when queried through "anime" and "charcter" . (the default "/api/quotes" remains the same. It still works on pagination)

**Comment by valkyrie-max** [comment]
You are truly a magician!

**Comment by RocktimSaikia** [comment]
@valkyrie-max  You are just being nice lol. I am closing this issue for now.
