### ISSUE TITLE
Shutting down animechan api !

### ISSUE THREAD

**Issue by RocktimSaikia** [RocktimSaikia/anime-chan#29]
![isuee](https://user-images.githubusercontent.com/33410545/97674724-0083b880-1ab4-11eb-99f8-f0213b943d5f.png)

Animechan was a personal project that I made public in 2019 since there was not any active API that serves anime quotes. I was hosting it on Heroku on **`free dynos`** since I initially didn't think that so many people would use it but recently due too many daily requests my **`free dynos quota exhausted`**. 

Since I am just a college student I don't want to spend a few more bucks on adding a paid dyno plan, therefore I have no choice but to stop the API service **`unless someone using this API is willing to financially back it.`**

#### To get in contact with me please email me at **`rocktimthedev@gmail.com`**

**Comment by RocktimSaikia** [comment]
For the time being, I'm making the services active again. But It's still free dynos, So the services may stop at any time once the free dyno hours are used completely.

**Comment by zedxos** [comment]
WHYYYYY I LOVE THIS I HAVENT YUSED THE API YET BUT IK THIS WAS SO GOOOOD

**Comment by RocktimSaikia** [comment]
@zedxos It's still running actually but on free dynos. So it gets stopped once it hits a month's request quota. I have some plans on improving the overall API in the future but not at the moment.

**Comment by zedxos** [comment]
> @zedxos It's still running actually but on free dynos. So it gets stopped once it hits a month's request quota. I have some plans on improving the overall API in the future but not at the moment.

Oh yeah srry i just got an error i thought it was really shuts down
