### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by Kadantte** [RocktimSaikia/anime-chan#38]
@RocktimSaikia is it possible to host our deployment? if yes can you please provide me with the way you're putting quotes into ur database or share with us the database dumb if it's okay with your ofc!

**Comment by RocktimSaikia** [comment]
Sharing the database will make this API redundant. Also, the database is not constant. I personally update and manage it frequently which is pretty time-consuming. So No I don't plan to make it public. Also, Animechan v2 is ready for deployment now. I will release it as soon as I am done with the release documentation. There are a lot of changes in the new version. Domian will change too. So it's taking time to document and manage all of that by myself.

**Comment by Kadantte** [comment]
Yeah, you're right, I just checked version 2 and it looks like u add an option to seed some data into the database so that should help with anyone who wants to make his data anyway I'll start on making some of one data and see this will be on my local database tho! and looks hard to put those quotes manually into `quote.json` I hope if there's a way to make it like there's an option to make easier to do so, Also thanks for making this lovely API and thank you for your hard work too!

**Comment by RocktimSaikia** [comment]
New API is up.
