### ISSUE TITLE
New routes needed !

### ISSUE THREAD

**Issue by RocktimSaikia** [RocktimSaikia/anime-chan#4]
@ritiksr25 Sir i need these api routes :

1) api/quotes?page=1 (done)

2) api/quotes/random (done)

3) api/quotes?anime='anime+name+here'  [TODO]
this will filter the database with the anime name provided by user. and returns all the filtered anime.

**Comment by ritiksr25** [comment]
api/quotes?anime='anime+name+here' will be in api/quotes as you just pass the "anime" query and results will be filtered!
- Do you want case ignorance and regex search?
ex: if anime = "blea" then results search "Bleach"?

**Comment by RocktimSaikia** [comment]
that's what i though too. but wasn't sure if it should be implemented the same way.
