### ISSUE TITLE
How to use in python bot

### ISSUE THREAD

**Issue by Suzie97** [RocktimSaikia/anime-chan#42]
I am a complete noob to python and I just want to use this API in my bot.

``` python
import discord
import os
import requests
import json

client = discord.Client ()

def get_quote ():
  response = requests.get ('https://animechan.vercel.app/api/random')
        .then(response => response.json())
        .then(quote => console.log(quote))
  return (quote)

@client.event
async def on_ready ():
  print ("We have logged in as {0.user}".format (client))

@client.event
async def on_message (message):
  if message.author == client.user:
    return

  if message.content.startswith ("$inspire"):
    quote = get_quote ()
    await message.channel.send (quote)

client.run (os.getenv ('TOKEN'))
``` 
This is how I try to make the API. And yeah it doesn't work. 

I know the problem is with this function:
``` python
def get_quote ():
  response = requests.get ('https://animechan.vercel.app/api/random')
        .then(response => response.json())
        .then(quote => console.log(quote))
  return (quote)
```
Can you tell me how to solve it?

**Comment by Kadantte** [comment]
This won't do it here you're using JS inside of python! All you did is you change fetch to response!
```js
response = requests.get ('https://animechan.vercel.app/api/random')
        .then(response => response.json())
        .then(quote => console.log(quote))
```

**Comment by Kadantte** [comment]
Here you go this is a working version!
```python
import discord
import os
import requests
import json

client = discord.Client ()

def get_animes():
  response = requests.get("https://animechan.vercel.app/api/random")
  json_data = json.loads(response.text)
  print(json_data)
  return json_data

@client.event
async def on_ready ():
  print ("We have logged in as {0.user}".format (client))

@client.event
async def on_message (message):
  if message.author == client.user:
    return

  if message.content.startswith ("$random"):
    quote = get_animes ()
    await message.channel.send (quote)

client.run('PUT_YOUR_TOKEN_HERE')
```
![image](https://user-images.githubusercontent.com/11579313/113202062-3515bf00-9262-11eb-820b-8ba9a09be07e.png)

now All you need to do is to look for a way to make your bot-message looks good :3

**Comment by Suzie97** [comment]
> 
> 
> Here you go this is a working version!
> 
> ```python
> import discord
> import os
> import requests
> import json
> 
> client = discord.Client ()
> 
> def get_animes():
>   response = requests.get("https://animechan.vercel.app/api/random")
>   json_data = json.loads(response.text)
>   print(json_data)
>   return json_data
> 
> @client.event
> async def on_ready ():
>   print ("We have logged in as {0.user}".format (client))
> 
> @client.event
> async def on_message (message):
>   if message.author == client.user:
>     return
> 
>   if message.content.startswith ("$random"):
>     quote = get_animes ()
>     await message.channel.send (quote)
> 
> client.run('PUT_YOUR_TOKEN_HERE')
> ```
> 
> ![image](https://user-images.githubusercontent.com/11579313/113202062-3515bf00-9262-11eb-820b-8ba9a09be07e.png)
> 
> now All you need to do is to look for a way to make your bot-message looks good :3

Thanks a lot.
