### ISSUE TITLE
Anime request

### ISSUE THREAD

**Issue by NotFaizen** [rocktimsaikia/anime-chan#43]
Can you please add the anime Jujutsu Kaisen? I tried to get quotes from that anime with the API but it showed no related quotes found. [Proof](https://user-images.githubusercontent.com/83504931/121504514-e1fb7d80-ca03-11eb-852f-196ed0e55de1.png)

**Comment by TaheirAhmedAshraf** [comment]
My hero academia
Attack on Titan
Eureka seven
demon slayer
jujutsu kaisen

**Comment by NotFaizen** [comment]
> My hero academia
> Attack on Titan
> Eureka seven
> demon slayer
> jujutsu kaisen

> ``
