### ISSUE TITLE
There is a typo in the documentation site.

### ISSUE THREAD

**Issue by itstyonirwansyah** [rocktimsaikia/anime-chan#45]
Good morning. When I first saw the website of the API, I saw a typo inside the pagination part.

Here is the media I captured: 

![fries](https://user-images.githubusercontent.com/73389687/123784137-53429800-d901-11eb-8acd-bb1e3a94fa28.png)

I think it's supposed to look like this: `https://animechan.vercel.app/api/quotes/anime?title=naruto&page=2`.

By the way, nice API you got there for the community :)

**Comment by rocktimsaikia** [comment]
@itstyonirwansyah Thanks for reporting. Fixed it in a recent commit.

**Comment by itstyonirwansyah** [comment]
Thanks for reading my issue, I hope u have a good day.
