### ISSUE TITLE
Upcoming updates for Animechan

### ISSUE THREAD

**Issue by rocktimsaikia** [rocktimsaikia/anime-chan#54]
- [ ]  Open source the API code
- [ ]  Migrate the codebase to Typescript
- [ ]  Migrate the database to PostgreSQL
- [ ]  Write tests

If you have any queries regarding these changes leave a comment here

**Comment by Kadantte** [comment]
Why not just stick with mongodb?

**Comment by rocktimsaikia** [comment]
The performance of PostgreSQL is much better/faster than MongoDB. And it is scalable as the database grows. Also working with PostgreSQL is a learning curve for me too. That is why I picked Postgres.
