### ISSUE TITLE
Number of quotes

### ISSUE THREAD

**Issue by saimayunus925** [rocktimsaikia/anime-chan#56]
Hello! I recently used this project to make a "daily Cowboy Bebop quotes" project, but apparently when we get quotes from a specific anime, the API only gets 10 quotes by default. Is there a way to fetch more quotes? Thanks!

**Comment by rocktimsaikia** [comment]
No, currently the API is not supplying more than 10 quotes. But we are considering changing it in the next update. In the meantime, you can use pagination to get the next set of 10 quotes if available.
```sh
https://animechan.vercel.app/api/quotes/anime?title=naruto&page=2
```
Check out https://animechan.vercel.app/guide for more info.
