### ISSUE TITLE
Make a min/max word or character limit for quotes.

### ISSUE THREAD

**Issue by tortendes** [rocktimsaikia/anime-chan#60]
### Why
When I was making a Notion "widget," I sometimes noticed the quotes got too big that it broke my styling.  This could help those issues by adding a min or even just a maximum limit parameter for quotes.

**Comment by zero-hundred** [comment]
Word would be difficult due to the length of words being varied. It may be a combination of the two where the character limit would respond with a quote whose total length is within the max limit.
Either way that's a good idea.

**Comment by rocktimsaikia** [comment]
These conditions can be added to the application level itself.
