### ISSUE TITLE
Open source?

### ISSUE THREAD

**Issue by Diogovski** [rocktimsaikia/anime-chan#61]
Is the database open source? the current request limit, limits my usage of the api.

**Comment by souzx17** [comment]
UP

**Comment by Aynh** [comment]
You can use my service (https://lascquotes.netlify.app) if you want, but the API is quite different and there is no filtering (It's in my TODO) and is also closed-source.

The API is `https://lascquotes.netlify.app/:count` where `count` is a number and represents how many quotes you want to fetch, if you omit or supplied an invalid number as `count` you will get _everything_ instead. You can also add `pretty` query parameter if you want them to be pretty printed.

**Comment by Diogovski** [comment]
Thx, but i already made my own with filter

A quinta, 1/09/2022, 06:43, Aynh ***@***.***> escreveu:
