### ISSUE TITLE
New python wrapper

### ISSUE THREAD

**Issue by Nekidev** [rocktimsaikia/anime-chan#63]
Hi! I made a python `>=3.7` API wrapper for Animechan since there are lots of people asking for help.

The documentation can be found at https://github.com/Nekidev/anime-api/tree/main/docs#animechan-api

It is very simple to use:
```python3
from anime_api.apis import AnimechanAPI

api = AnimechanAPI()

# Get a quote
quote: Quote = api.get_random_quote()

# Get 10 quotes
quotesList[Quote] = api.get_many_random_quotes()

# Search by anime title. The page is 1 by default if not specified
quotes: Quote = api.search_by_anime_title(anime_title="Toradora", page=1)

# Search by character name. The page is 1 by default
quotes: List[Quote] = api.search_by_character_name(character_name="Misaki", page=1)

# Get list of animes
animes: List[str] = api.get_animes()
```

I hope someone finds this useful as there were many who were finding difficult to make an http request.

**Comment by rocktimsaikia** [comment]
Closing this as this is already added in the readme
