### ISSUE TITLE
Available Anime And Character List

### ISSUE THREAD

**Issue by VasuGarg07** [rocktimsaikia/anime-chan#67]
The available endpoint has been removed recently.

Is the endpoint removed permanently or will you enable it again. As this endpoint really helpful (and even required to some extent) in my project. Also, if possible, can you provide an endpoint for available character list of an anime who's quotes are available

**Comment by rocktimsaikia** [comment]
I see. I removed it because the implementation for that route was not correct. It was not dynamic meaning adding new animes didn't update the anime list of that endpoint. I will work on it and release it soon.

**Comment by nagy-nabil** [comment]
@rocktimsaikia  if you're not working on this end point rn I can give it a try

**Comment by melosh101** [comment]
Currently it seems that rocktim is away. I currently have a pr with the same feature but for the list of animes. I've been trying to find a good way to implement this feature with as small of a query time as possible and I think I'm about there, so I might add it to that pr and notify rocktim about it.

**Comment by rocktimsaikia** [comment]
This was added in recently. Both available Anime and Characters endpoints are added.
https://animechan.vercel.app/docs#available-anime
https://animechan.vercel.app/docs#available-characters
