### ISSUE TITLE
Code style and refactor

### ISSUE THREAD

**Issue by ritiksr25** [RocktimSaikia/anime-chan#7]
The code structure can be improved and refactored with the following changes:
- using separate route and controllers
- standard response format, ex: { message: "success", error: "false", data: [] }
- 404 route

**Comment by RocktimSaikia** [comment]
@ritiksr25 great suggestions. Please separate it with controllers and nested routes. And i already added 404 in branch. will push soon :tada:

**Comment by ritiksr25** [comment]
Done!!

**Comment by RocktimSaikia** [comment]
@ritiksr25 I formatted/prettified the return json data for better usage.
