### ISSUE TITLE
List of existing animes with quotes.

### ISSUE THREAD

**Issue by MCJUNIORLK** [rocktimsaikia/anime-chan#73]
![Screenshot_20221207-120558_Discord~2](https://user-images.githubusercontent.com/76866792/206163352-cfd29cf0-d93f-4bd2-bdac-23d82ac937e1.jpg)
(I would volunteer to help if help is needed)

**Comment by rocktimsaikia** [comment]
This was added in recently. Both available Anime and Characters endpoints are added.
https://animechan.vercel.app/docs#available-anime
https://animechan.vercel.app/docs#available-characters
