### ISSUE TITLE
showing too many requests error on hitting this url - "https://animechan.xyz/api/random", status code:429

### ISSUE THREAD

**Issue by Rigved29** [rocktimsaikia/anime-chan#80]
@rocktimsaikia please check.

**Comment by lennyAiko** [comment]
Hello @Rigved29 

It is most likely the rate limit

**Comment by pab-h** [comment]
As @lennyAiko  said, it's an API limitation.

As I've used the API, I've noticed that the maximum of 100 requests per hour is for ALL clients. So, if @Rigved29  and I made a request at the same time, the API would count it as 2 of the 100 requests allowed. But, I'm not sure of this information since we don't have access to the source code. 

@rocktimsaikia, could you verify my theory? 

If that's true, that's why "Too many requests" happens quite often.

**Comment by rocktimsaikia** [comment]
Yes. That's true. it's documented on the website also. This rate limit is required since this is a free service but running at my own cost on AWS.

![image](https://github.com/rocktimsaikia/anime-chan/assets/33410545/47d404f9-13d7-4d6f-b43a-548fe8858e5b)

**Comment by rocktimsaikia** [comment]
FYI, I am rewriting the API. I will change some behaviours. And hopefully open source the backend.

**Comment by pab-h** [comment]
Thank you for your reply. Please know that you can count on our support, @rocktimsaikia

**Comment by rocktimsaikia** [comment]
The rate limit refactoring was done by @melosh101 later in Animechan's private backend repo. since I am quite busy these days, maybe he can look into the issue you mentioned above:
> I made a request at the same time, the API would count it as 2 of the 100 requests allowed

**FYI, the whole codebase is public now.**

**Comment by melosh101** [comment]
after some investigation it looks like when it backend source was released to the public ratelimits where disabled, ill be looking into re-implementing ASAP, might be my christmas present to the world

**Comment by rocktimsaikia** [comment]
@melosh101 I missed that. That rate-limit is very important tbh. Can you implement a basic rate-limit with something like https://www.npmjs.com/package/koa-ratelimit with system memory for now. Later we can move to a remote Redis host.

**Comment by melosh101** [comment]
Ill look into it, but its getting late here, it's 5am 😅

**Comment by rocktimsaikia** [comment]
This should be fixed now. Closing for now
