### ISSUE TITLE
Unable to access documentation (also possibly the API)

### ISSUE THREAD

**Issue by edwar3je** [rocktimsaikia/anime-chan#81]
I recently tried to access the documentation to see how to make simple requests to obtain a few quotes (link at https://animechan.xyz/), however I received the following message on the page: "502 Bad Gateway". Is there an updated link for the documentation? If not, could you provide the API calls needed to obtain quotes?

**Comment by rocktimsaikia** [comment]
The AWS EC2 instance had no space. I had to upgrade it to a larger-sized instance type. Anyway, it's up now.

**Comment by edwar3je** [comment]
Thanks, that really helps!
